version: 2.1
orbs:
  node: circleci/node@4.5
jobs:
  release:
    executor:
      name: node/default
      tag: 20.11.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npx semantic-release

workflows:
  test_and_release:
    jobs:
      - node/test:
          pkg-manager: npm
          matrix:
            parameters:
              version:
                - 20.11.0
      - release:
          requires:
            - node/test
