version: 2.1
orbs:
  node: circleci/node@4.5
jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: npx semantic-release

workflows:
  test_and_release:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 16.1.0
                - 14.7.0
      - release:
          requires:
            - node/test
          filters:
            branches:
              only: main
