version: 2.1
orbs:
  node: circleci/node@4.5
jobs:
  release:
    executor:
      name: node/default
      tag: 14.7.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: npx semantic-release

workflows:
  test_and_release:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 16.1.0
                - 14.7.0
      - release:
          requires:
            - node/test
          filters:
            branches:
              only: main
